---
# tasks file for register_rhel_subscription

- name: Register RHEL instance subscription
  redhat_subscription:
    state: present
    activationkey: "{{ rh_activationkey }}"
    org_id: "{{ rh_org_id }}"
    release: "{{ rh_release }}"
    auto_attach: true
  when: rh_register
  register: rhsm_output

- name: Enable RHEL repos (RHEL 8)
  rhsm_repository: name={{item}} state=enabled
  with_items:
    - rhel-{{ansible_distribution_major_version}}-for-{{ansible_architecture}}-baseos-rpms
    - rhel-{{ansible_distribution_major_version}}-for-{{ansible_architecture}}-appstream-rpms
    - rhel-{{ansible_distribution_major_version}}-for-{{ansible_architecture}}-supplementary-rpms
    - codeready-builder-for-rhel-{{ansible_distribution_major_version}}-{{ansible_architecture}}-rpms
  when: ansible_distribution_major_version|int == 8

- debug:
    msg: "{{ rhsm_output }}"

- name: Unregister RHEL instance subscription
  redhat_subscription:
    state: absent
    activationkey: "{{ rh_activationkey }}"
    org_id: "{{ rh_org_id }}"
  when: not rh_register
  register: rhsm_output

- debug:
    msg: "{{ rhsm_output }}"
