---
# tasks file for register_rhel_subscription

- name: Register RHEL instance subscription
  redhat_subscription:
    state: present
    activationkey: "{{ rh_activationkey }}"
    org_id: "{{ rh_org_id }}"
    auto_attach: true
  when: rh_register

- name: Unregister RHEL instance subscription
  redhat_subscription:
    state: absent
    activationkey: "{{ rh_activationkey }}"
    org_id: "{{ rh_org_id }}"
  when: not rh_register