---
# tasks file for register_rhel_subscription

- name: Register RHEL instance subscription
  redhat_subscription:
    state: present
    activationkey: "{{ rh_activationkey }}"
    org_id: "{{ rh_org_id }}"
    release: "{{ rh_release }}"
    auto_attach: true
  register: reg_sub
  until: reg_sub is not failed
  retries: 5
 
- name: Update stage to registered
  set_fact:
    provisioning_stage: "registered"
    cacheable: yes
  when: reg_sub is not failed
