---
# tasks file for register_rhel_subscription
- name: "remove rhui"
  ansible.builtin.yum:
    name: rh-amazon-rhui-client*
    state: absent
  become: yes

- name: "start rhsmcertd"
  ansible.builtin.systemd:
    name: rhsmcertd
    enabled: yes
    state: started
  become: yes

- name: Register RHEL instance subscription
  redhat_subscription:
    state: present
    activationkey: "{{ rh_activationkey }}"
    org_id: "{{ rh_org_id }}"
    release: "{{ rh_release }}"
    auto_attach: true
    pool_ids: "{{ pool_ids | default(omit) }}"
  become: yes
  register: reg_sub
  until: reg_sub is not failed
  retries: 5

- name: "check registration status"
  ansible.builtin.shell: >
    subscription-manager status |
    grep "Overall Status:"
  register: sub_status

- name: "subscription-manager refresh"
  ansible.builtin.command: >
    subscription-manager refresh
  when: '"Current" in sub_status.stdout'

- name: "subscription-manager update facts"
  ansible.builtin.command: >
    subscription-manager facts
    --update
  when: '"Current" in sub_status.stdout'

- name: Update stage tag to registered
  ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ hostvars[inventory_hostname]['ec2_id'] }}"
    state: present
    tags:
      Stage: "registered"
  delegate_to: localhost
  when: reg_sub is not failed
