---
# tasks file for register_rhel_subscription
- name: "remove rhui"
  ansible.builtin.yum:
    name: rh-amazon-rhui-client*
    state: absent
  become: yes

- name: "start rhsmcertd"
  ansible.builtin.systemd:
    name: rhsmcertd
    enabled: yes
    state: started
  become: yes

- name: set repos to managed
  ansible.builtin.command: >
    subscription-manager config 
    --rhsm.manage_repos=1
  become: yes  

- name: "check registration status"
  ansible.builtin.shell: >
    subscription-manager status |
    grep "Overall Status:" |
    awk -F': ' '{print $2}'
  register: sub_status
  become: yes  

- name: Create system_name
  set_fact:
    system_name: "{{ hostvars[inventory_hostname]['tags']['Name'] | replace(' ', '_') }}"

- name: register with customer portal
  ansible.builtin.command: >
    subscription-manager register 
    --activationkey="{{ rh_activationkey }}"
    --org="{{ rh_org_id }}"
    --name="{{ system_name }}"
  become: yes

- name: register insights client
  ansible.builtin.command: >
    insights-client 
    --register 
    --display-name "{{ system_name }}"
  become: yes  

#- name: Register RHEL instance subscription
#  redhat_subscription:
#    state: present
#    activationkey: "{{ rh_activationkey }}"
#    org_id: "{{ rh_org_id }}"
#    release: "{{ rh_release }}"
##    auto_attach: true
#    pool_ids: "{{ pool_ids | default(omit) }}"
#    consumer_name: "{{ consumer_name }}"
#  
#  register: reg_sub
#  until: reg_sub is not failed
#  retries: 5

- name: "subscription-manager refresh"
  ansible.builtin.command: >
    subscription-manager refresh
  when: '"Current" in sub_status.stdout'
  become: yes

- name: "subscription-manager update facts"
  ansible.builtin.command: >
    subscription-manager facts
    --update
  when: '"Current" in sub_status.stdout'
  become: yes

- name: Update stage tag to registered
  ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ hostvars[inventory_hostname]['instance_id'] }}"
    state: present
    tags:
      Stage: "registered"
  delegate_to: localhost
  when: reg_sub is not failed
