---
# tasks file for register_rhel_subscription
- name: "remove rhui"
  ansible.builtin.yum:
    name: rh-amazon-rhui-client*
    state: absent

- name: "start rhsmcertd"
  ansible.builtin.systemd:
    name: rhsmcertd
    enabled: yes
    state: started

- name: Register RHEL instance subscription
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ rh_activationkey }}"
    org_id: "{{ rh_org_id }}"
    release: "{{ rh_release }}"
    auto_attach: true
    pool_ids: "{{ pool_ids | default(omit) }}"
  become: yes
  register: reg_sub
  until: reg_sub is not failed
  retries: 5

- name: Update stage tag to registered
  amazon.aws.ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ hostvars[inventory_hostname]['ec2_id'] }}"
    state: present
    tags:
      Stage: "registered"
  delegate_to: localhost
  when: reg_sub is not failed
